#pragma config(Sensor, dgtl1,  ,               sensorTouch)
#pragma config(Motor,  port2,           leftWheels,    tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,            ,             tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port4,            ,             tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port5,            ,             tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port6,           liftSystem,    tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port7,            ,             tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port8,           rightWheels,   tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port9,            ,             tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
    
    while(true)
    {
            
            //Wheel Controls
            motor[port8] = vexRT[Ch2]; //Right Wheels
            motor[port2] = -vexRT[Ch3];	//Left Wheels Reversed

            if(vexRT[Btn6U] == true) { //Move the body up
                motor[port6] = 127;
            
            } else if(vexRT[Btn6D] == true) { //Move the body down
                motor[port6] = -127;
            
            } else { //Keep the body in  place
                motor[port6] = 0;
            }
    }
    
}
