#pragma config(Motor,  port3,            ,             tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port4,            ,             tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port5,            ,             tmotorServoContinuousRotation, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true){
		motor[port5] = vexRT[Ch2];
		motor[port3] = vexRT[Ch3];

		if(vexRT(Btn6U)){
			motor[port7] = -60;
			} else if(vexRT(Btn6D)){
			motor[port7] = 60;
			} else {
			motor[port7] = 0;
		}
	}
}
